// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvCHlAC9kpQdWlHRBVENj4Dk9W_w_8IN8',
    appId: '1:339633702899:web:5e4567c36b21eb8fccb486',
    messagingSenderId: '339633702899',
    projectId: 'flutter-home-de5eb',
    authDomain: 'flutter-home-de5eb.firebaseapp.com',
    storageBucket: 'flutter-home-de5eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMAyWCRph1tk4tXHfWz242ALUWCpaLTXY',
    appId: '1:339633702899:android:fdcd4f874e07b105ccb486',
    messagingSenderId: '339633702899',
    projectId: 'flutter-home-de5eb',
    storageBucket: 'flutter-home-de5eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvAtht0N0RwYIRgPBvSY1RXnUmXZiVYVQ',
    appId: '1:339633702899:ios:be0827fd2d273e06ccb486',
    messagingSenderId: '339633702899',
    projectId: 'flutter-home-de5eb',
    storageBucket: 'flutter-home-de5eb.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvAtht0N0RwYIRgPBvSY1RXnUmXZiVYVQ',
    appId: '1:339633702899:ios:be0827fd2d273e06ccb486',
    messagingSenderId: '339633702899',
    projectId: 'flutter-home-de5eb',
    storageBucket: 'flutter-home-de5eb.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvCHlAC9kpQdWlHRBVENj4Dk9W_w_8IN8',
    appId: '1:339633702899:web:4f62566bd69822b1ccb486',
    messagingSenderId: '339633702899',
    projectId: 'flutter-home-de5eb',
    authDomain: 'flutter-home-de5eb.firebaseapp.com',
    storageBucket: 'flutter-home-de5eb.firebasestorage.app',
  );
}
